In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [16]:
df = pd.read_csv("C://Users//Ananthram Vasu//Downloads//NLP Project//chatgpt_reviews - chatgpt_reviews.csv")
df.head(10)

,date,title,review,rating,username,helpful_votes,review_length,platform,language,location,version,verified_purchase
0,2/15/2025,Impressive,Mother former community upon vote fact. Sure s...,2,ybass,68,78,Mobile,es,Canada,3.0,No
1,10/16/2024,Waste of Time,General paper understand main. Or age half won...,5,glenn33,71,193,Web,de,India,4.1,Yes
2,10/16/2024,Waste of Time,Here situation his high stage. Agree certainly...,4,debbie27,66,184,Web,hi,India,4.1,Yes
3,12/21/2024,Not Accurate,Rule court behind growth reality. Tonight whos...,1,hannahrussell,5,193,Web,fr,Canada,4.0,Yes
4,3/23/2025,Fantastic Experience,Case opportunity season road write. Effort gre...,3,cnorton,71,131,Web,hi,Australia,4.1,No
5,8/20/2024,Not Accurate,Top position able wear its between kid. Number...,5,paulroberts,57,128,Web,fr,Australia,4.1,Yes
6,9/15/2024,Very Helpful,Brother individual process always. Sing behind...,1,emilydrake,65,188,Mobile,en,Canada,3.5,Yes
7,11/22/2024,Needs Improvement,Upon bit pick. Seven along unit local these. C...,3,deborah04,22,172,Web,de,Canada,4.0,No
8,11/5/2024,Fantastic Experience,Number choice student production son understan...,4,marckennedy,69,77,Web,hi,India,3.0,Yes
9,8/11/2024,Not Accurate,Stand space approach southern.\nGlass federal ...,4,katherine46,70,100,Web,en,Germany,3.5,Yes

In [17]:
df['review'][1]

'General paper understand main. Or age half wonder positive senior. Book agency professional over alone away sit.\nAfter like law policy than what news. Book moment hour approach kind future ten.'

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               10000 non-null  object
 1   title              10000 non-null  object
 2   review             10000 non-null  object
 3   rating             10000 non-null  int64
 4   username           10000 non-null  object
 5   helpful_votes      10000 non-null  int64
 6   review_length      10000 non-null  int64
 7   platform           10000 non-null  object
 8   language           10000 non-null  object
 9   location           10000 non-null  object
 10  version            10000 non-null  float64
 11  verified_purchase  10000 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 937.6+ KB

In [9]:
df.isnull().sum()

date                 0
title                0
review               0
rating               0
username             0
helpful_votes        0
review_length        0
platform             0
language             0
location             0
version              0
verified_purchase    0
dtype: int64

In [24]:
#Create Sentiment Labels from Ratings
def label_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"

In [12]:
df.head()

,date,title,review,rating,username,helpful_votes,review_length,platform,language,location,version,verified_purchase,sentiment
0,2/15/2025,Impressive,Mother former community upon vote fact. Sure s...,2,ybass,68,78,Mobile,es,Canada,3.0,No,Negative
1,10/16/2024,Waste of Time,General paper understand main. Or age half won...,5,glenn33,71,193,Web,de,India,4.1,Yes,Positive
2,10/16/2024,Waste of Time,Here situation his high stage. Agree certainly...,4,debbie27,66,184,Web,hi,India,4.1,Yes,Positive
3,12/21/2024,Not Accurate,Rule court behind growth reality. Tonight whos...,1,hannahrussell,5,193,Web,fr,Canada,4.0,Yes,Negative
4,3/23/2025,Fantastic Experience,Case opportunity season road write. Effort gre...,3,cnorton,71,131,Web,hi,Australia,4.1,No,Neutral

In [14]:
df.drop(columns=['helpful_votes', 'platform', 'version', 'verified_purchase'])

,date,title,review,rating,username,review_length,language,location,sentiment
0,2/15/2025,Impressive,Mother former community upon vote fact. Sure s...,2,ybass,78,es,Canada,Negative
1,10/16/2024,Waste of Time,General paper understand main. Or age half won...,5,glenn33,193,de,India,Positive
2,10/16/2024,Waste of Time,Here situation his high stage. Agree certainly...,4,debbie27,184,hi,India,Positive
3,12/21/2024,Not Accurate,Rule court behind growth reality. Tonight whos...,1,hannahrussell,193,fr,Canada,Negative
4,3/23/2025,Fantastic Experience,Case opportunity season road write. Effort gre...,3,cnorton,131,hi,Australia,Neutral
...,...,...,...,...,...,...,...,...,...
9995,6/13/2024,Very Helpful,Little section hit her through. Likely job ind...,5,john32,83,de,Australia,Positive
9996,7/16/2024,Buggy,Throw with record relationship help reduce vot...,3,michael25,189,es,Germany,Neutral
9997,7/22/2024,Not Accurate,Within nothing study charge all. Toward milita...,3,sean13,185,de,India,Neutral
9998,5/24/2024,Needs Improvement,Rule kitchen trouble cultural.\nDeep manage ad...,3,pjones,163,fr,UK,Neutral
9999,2/17/2025,Fantastic Experience,Resource plant behind vote its try laugh. Othe...,2,brownadrienne,81,en,Germany,Negative

In [20]:
df=df.drop(columns=['helpful_votes', 'platform', 'version', 'verified_purchase'])

In [26]:
df.columns

Index(['date', 'title', 'review', 'rating', 'username', 'review_length',
       'language', 'location', 'sentiment'],
      dtype='object')

In [25]:
df['sentiment'] = df['rating'].apply(label_sentiment)

In [32]:
X=df['review']
y=df['sentiment']

In [33]:
cv = CountVectorizer()
X = cv.fit_transform(X) # Fit the Data

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [35]:
clf = MultinomialNB()
clf.fit(X_train,y_train)

MultinomialNB()

In [49]:
df['review'][10]

'Wait address exactly push film. Prevent growth appear tell western PM. Trial unit concern before.'

In [50]:
data = cv.transform(['Wait address exactly push film. Prevent growth appear tell western PM. Trial unit concern before.']).toarray()
a = clf.predict(data)
print(a)

['Negative']

In [42]:
import pickle
# Save the model
with open('NLP_Model.pkl', 'wb') as file:
    pickle.dump(clf, file)

In [46]:
with open('vectorizer.pkl', 'wb') as file:
    pickle.dump(cv, file)